### ISSUE TITLE
Consider uploading ssw to PyPi? 

### ISSUE THREAD

**Issue by ksahlin** [vishnubob/ssw#2]
Hi, 

I want to include this library as dependence in my code. Could you consider uploading a version to PyPi everytime you make an update (that is of relatively significant importance).

It would be great since then we can just issue `pip install ssw` (and also it's easier to include the dependency on this library in the setup.py script when pip installs my software).
Another big pro is that you can run `pip uninstall` or `pip install --upgrade` on ssw. Now I need to go in and remove the files manually whenever in need to install a new update of ssw (at least I dont know any other way to remove the library if I want to install a new version).  

Kindly,
Kristoffer

**Comment by vishnubob** [comment]
[done](https://pypi.python.org/pypi?:action=display&name=ssw&version=0.3.1)

**Comment by ksahlin** [comment]
Perfect! Thanks
