### ISSUE TITLE
Speed enhancement

### ISSUE THREAD

**Issue by ksahlin** [vishnubob/ssw#4]
Hi again,

I'm currently calculating lots of align instances with your library. I did some profiling of my code and noticed that there might be room for speed improvement without significant rewriting. When I studied the profiling stats (attached below), it seems like the alignment parser `sswobj.py:149(alignment)` and converting sequences to ints `convert_sequence_to_ints` pretty much takes up all the overhead time. 
- My intuition tells me that at least the speed of the `alignment` function can be greatly reduced e.g. by omitting `sswobj.py:153(getseq)` completely --- maybe r_seq and q_seq can be made strings immediately and operated on?
- Maybe also some of the `.upper()` calls can be skipped or be made once for an entire string? I see that there are a huge amount of calls to `upper()` for my instance 309373840, for only 88409 calls to align. Maybe .upper() can be called once on a entire string?
- I have no idea for now to why `convert_sequence_to_ints` takes the time it does, but my intuition tells me that the time spent in it can be improved :)

I will eventually look into this myself, but thought I should let you know --- maybe you have some quick insights?

```
   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      2/1    0.097    0.048  491.491  491.491 runHIT:30(<module>)
        1    0.040    0.040  490.521  490.521 runHIT:74(get_alignment_information)
        1    2.234    2.234  480.330  480.330 transcript_module.py:155(get_alignments_from_SW)
    88409    0.418    0.000  285.299    0.003 sswobj.py:90(align)
    88410  168.563    0.002  284.786    0.003 sswobj.py:107(_align)
    88412   52.584    0.001  158.666    0.002 sswobj.py:149(alignment)
   176820   54.718    0.000  113.293    0.001 sswobj.py:61(convert_sequence_to_ints)
  4601464   28.244    0.000   76.336    0.000 sswobj.py:153(getseq)
156490544   45.569    0.000   58.548    0.000 sswobj.py:63(<genexpr>)
160414072   35.748    0.000   48.092    0.000 sswobj.py:154(<genexpr>)
    88409    0.499    0.000   33.352    0.000 collections.py:441(__init__)
    88409   26.037    0.000   32.853    0.000 collections.py:504(update)
309373840   25.654    0.000   25.654    0.000 {method 'upper' of 'str' objects}
155812906   12.345    0.000   12.348    0.000 {next}
  3126588    7.235    0.000   10.923    0.000 sswobj.py:131(iter_cigar)
.....
```

**Comment by vishnubob** [comment]
I just pushed a commit that provided a considerable speed up of `convert_sequence_to_ints`, but the the speed up of `alignment_report` is much trickier.  One problem I know about is that the header of `alignment_report` essentially calls `alignment` three times (first for the match count, second for the mismatch count, and third for the report itself).  The problem is that the CIGAR string does not differentiate between matched and mismatched bases, only that bases align.  The reason I'm calling `upper` so much is to preserve the upper/lower case of input sequences in the subsequent report.  The `getseq()` closure is a convenience, and really doesn't lend to itself to the inefficiencies you are experiencing.  I've thought about caching the results, but I also wanted to avoid memory bloat.  A quick win to try is setting the `header=False` on the `alignment_report`, or just using the `alignment` property, and formatting your own version of the content.

**Comment by ksahlin** [comment]
Great, Thanks!

I fixed a speedup to `alignment()`. I have only profiled one data set, where it seems to give about 2x speedup.

```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
88540   49.172    0.001   82.287    0.001 sswobj.py:185(alignment)
```

Compare to the same profile row in previous post:
`88412   52.584    0.001  158.666    0.002 sswobj.py:149(alignment)`

I noticed slightly more calls to the new run but that should be change in the parameters in my software, i.e., not related to the alignment function itself (if does not call itself) . I did `assert` on the output of yours and mine alignment function and it passed all of my 3700 alignments (biological data), hopefully it will pass your unittests as well. Could you consider using this function instead? The function is found here:
https://gist.github.com/ksahlin/76a16f0b6fa19988b1db

**Comment by ksahlin** [comment]
correction: should be "it does not call itself"

**Comment by ksahlin** [comment]
Hi again, I did a further optimization in the `alignment()` function, specifically of the match string parsing as:

`match_seq = ''.join(['|' if r_base.upper() == q_base.upper() else '*' for (r_base, q_base) in zip(ref_piece, query_peace)])` 

see gist https://gist.github.com/ksahlin/3b740b78d1d80cbd20be
new benchmark: 

```
    88540   35.453    0.000   61.895    0.001 sswobj.py:185(alignment)
```

**Comment by ksahlin** [comment]
Hi again,

could you consider including the function i attached in the gist in your repo?

**Comment by Chris7** [comment]
@ksahlin why not fork it and submit a PR?

**Comment by ksahlin** [comment]
@Chris7 Ok! Done in https://github.com/vishnubob/ssw/pull/5

**Comment by vishnubob** [comment]
Thanks for this PR, this has been integrated.
